### ISSUE TITLE
Question: Why is StateEventWithContent  implemented as an abstract class?

### ISSUE THREAD

**Issue by yshrsmz** [leonard-palm/compose-state-events#1]
Hi, thanks for your inspiring work!

One question; Why is StateEventWithContent implemented as an abstract class instead of sealed interface/class?

**Comment by leonard-palm** [comment]
Hi, 
good point, I overlooked that. I implmented `StateEventWithContent` as a `sealed interface` in v1.2.3 to enabled exaustive when statements. I don't see any reason at the moment why one would need to extend `StateEventWithContent`.
