### ISSUE TITLE
Is this library still being maintained?

### ISSUE THREAD

**Issue by dave08** [leonard-palm/compose-state-events#10]

**Comment by leonard-palm** [comment]
Hi @dave08 
Do you need something in specific or do you think something is too outdated?

**Comment by dave08** [comment]
Since the last commit was a year ago, I was wondering if something is replacing it...  do you still use this library? 

Also, usually at least dependencies are updated (which sometimes can cause conflicts in Android and other platforms...).

**Comment by leonard-palm** [comment]
@dave08 
Yes it is still in use. Let me know if you see any bigger (library-breaking) problems with newer android/compose versions. 

A dependency update is probably a good idea. Feel free to open a PR.
