### ISSUE TITLE
How is the library used together with paging3?

### ISSUE THREAD

**Issue by mainrs** [leonard-palm/compose-state-events#5]
I have a Room DAO that has the following query. My ViewModel then defines the `Pager` instance I use inside my `ViewModel` as shown below:

```kotlin
/// DAO
@Query("SELECT * FROM <table> ORDER BY createdAt DESC")
fun getAllPaged(): PagingSource<Int, Model>

/// ViewModel
class MyViewModel: ViewModel() {
    val allItems = Pager(PagingConfig(pageSize = 10)) {
        myDao.getAllPaged()
    }.flow.cachedIn(viewModelScope)
}

/// UI
@Composable
fun MyContent(viewModel: MyViewModel = hiltViewModel()) {
    val items = viewModel.allItems.collectAsLazyPagingItems()
}
```

How do I keep the `Pager` lazy when adding it to the `ViewState` data class? I don't know if this is possible and by checking online I don't think it is.

**Comment by leonard-palm** [comment]
@mainrs I really dont see how your question/issue applies to any implementation of the compose-state-events library. 
The library doesnt dictate how to structure your ViewState object or your outgoing flows in your ViewModel class.
